kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-demo-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo-prod
  template:
    metadata:
      labels:
        app: devops-demo-prod
    spec:
      containers:
        - name: devops-demo-prod
          image: ryanpedersen42/devops-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
  
---

kind: Service
apiVersion: v1
metadata:
  name: devops-demo-prod
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: devops-demo-prod